AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Scraper-Service-MarketPulseAI

  Sample SAM Template for Scraper-Service-MarketPulseAI

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  ScraperServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: scraper_service/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Role: arn:aws:iam::829982859440:role/scraper-service-role
  ScraperServiceSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "cron(30 17 * * ? *)"  # 11 PM IST (5:30 PM UTC)
      Targets:
        - Arn: !GetAtt ScraperServiceFunction.Arn
          Id: "ScraperServiceTarget"
          InputTransformer:
            InputPathsMap:
              runDate: "$.time"  # Use the 'time' field from EventBridge, which contains the current time
            InputTemplate: '{"RunDate": <runDate>}'
  